### ISSUE TITLE
some question about login to download dataset

### ISSUE THREAD

**Issue by HU-xiaobai** [CSAILVision/GazeCapture#58] opened 2021-10-03 09:13 UTC
Dear Mr or Mrs,
Hello, I am a student of University of Edinburgh. This week I registered an account in your website ”eye track for everyone’’  and wanted to download the dataset. However, after I activating my account, I cannot login for trying many times and finally the website deny me visit. And also I email you but my email was returned because the email address is not exist. Could you help me solve the problem? How can I login and download the dataset?  My register email is 986045352@qq.com and My name is Zhanghao HU. Thanks for your reading!

**Comment by erkil1452** [comment] 2021-10-03 10:21
Hi Zhanghao, I am sorry you are having problems. It seems the issue is that your e-mail domain does not match your institution. Please try registering with your academic e-mail.

**Comment by HU-xiaobai** [comment] 2021-10-03 10:25
but now I can not enter your website to register the account, it always deny me.  how can I enter in?

**Comment by erkil1452** [comment] 2021-10-03 10:36
Your IP address must have been blocked. Either try a different IP address or let me unblock it.

**Comment by HU-xiaobai** [comment] 2021-10-03 10:40
Can you unblock my IP ? Because I only has one computer. Will it take a lot of time?

**Comment by erkil1452** [comment] 2021-10-03 11:02
No, just send me your IP address.

**Comment by HU-xiaobai** [comment] 2021-10-03 11:10
My ip address is:86.142.19.13




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CSAILVision/GazeCapture"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月3日(星期天) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CSAILVision/GazeCapture] some question about login to download dataset (#58)





 
No, just send me your IP address.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HU-xiaobai** [comment] 2021-10-03 11:11
ok I have send you ip address by my email

**Comment by HU-xiaobai** [comment] 2021-10-03 11:12
oppps, could you hide my ip?

**Comment by erkil1452** [comment] 2021-10-03 11:15
You should now have access.

**Comment by HU-xiaobai** [comment] 2021-10-03 11:26
Thanks a lot!
I will retry my register

**Comment by erkil1452** [comment] 2021-10-04 14:49
I hope the issue is resolved. I am closing the ticket.

**Closed as completed by erkil1452** 2021-10-04 14:49 UTC
